"""add temp password flag

Revision ID: 0871a8e6e5ba
Revises: b1d8e913570b
Create Date: 2026-01-31 16:58:57.049930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0871a8e6e5ba'
down_revision = 'b1d8e913570b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_doctor_date_time', ['doctor_profile_id', 'available_date', 'start_time', 'end_time'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_temp_password', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_temp_password')

    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_constraint('uq_doctor_date_time', type_='unique')

    # ### end Alembic commands ###
