"""Add contact_number to DoctorProfile

Revision ID: d354184aa527
Revises: c4caac075fd5
Create Date: 2025-11-30 02:25:45.315120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd354184aa527'
down_revision = 'c4caac075fd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_profile', schema=None) as batch_op:
        batch_op.drop_column('contact_number')

    # ### end Alembic commands ###
