"""Add visit_type and tests_done to Treatment table

Revision ID: e6ba31401de9
Revises: 
Create Date: 2025-11-10 01:29:18.970230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ba31401de9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tests_done', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.drop_column('doctor_notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_notes', sa.TEXT(), nullable=True))
        batch_op.drop_column('notes')
        batch_op.drop_column('tests_done')
        batch_op.drop_column('visit_type')

    # ### end Alembic commands ###
